const data = {
  products: [
    // Men
    {
      name: "gentleman 001",
      images: "https://i.postimg.cc/nLD2C3pq/gentleman-001.jpg",
      price: 9999,
      category: "men suit",
      rating: 4.5,
      menSuit: true,
      menPants: false,
      womanPants: false,
      womanSuits: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },
    {
      images: "https://i.postimg.cc/htS11VT7/gentlemen-002.jpg",
      name: "gentleman 002",
      price: 9999,
      category: "men suit",
      rating: 4.5,
      menSuit: true,
      menPants: false,
      womanPants: false,
      womanSuits: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },
    {
      images: "https://i.postimg.cc/C1jR2QVM/gentle-003.jpg",
      name: "gentleman 003",
      price: 9999,
      category: "men suit",
      rating: 4.5,
      menSuit: true,
      menPants: false,
      womanPants: false,
      womanSuits: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },
    {
      images: "https://i.postimg.cc/Bnv6mxKh/suit01.jpg",
      name: "suit 01",
      price: 9999,
      category: "men suit",
      rating: 4.5,
      menSuit: true,
      menPants: false,
      womanPants: false,
      womanSuits: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },

    {
      images: "https://i.postimg.cc/7ZLsbmfn/redSuit.jpg",
      name: "red Suit",
      price: 9999,
      category: "men suit",
      rating: 4.5,
      menSuit: true,
      menPants: false,
      womanPants: false,
      womanSuits: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },

    {
      images: "https://i.postimg.cc/XvLHr86d/yellow-Sult.jpg",
      name: "yellow Suit",
      price: 9999,
      category: "men suit",
      rating: 4.5,
      menSuit: true,
      menPants: false,
      womanPants: false,
      womanSuits: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },

    {
      images: "https://i.postimg.cc/Wzd7qVVJ/differentcolors.webp",
      name: "different colors",
      price: 9999,
      category: "men suit",
      rating: 4.5,
      menSuit: true,
      menPants: false,
      womanPants: false,
      womanSuits: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },
    //   woman-suit
    {
      images: "https://i.postimg.cc/hPFBvtxY/woman-sult-001.jpg",
      name: "woman-sult-001",
      price: 9999,
      category: "women suit",
      rating: 4.5,
      menSuit: false,
      menPants: false,
      womanPants: false,
      womanSuits: true,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },
    {
      images: "https://i.postimg.cc/2ySBB7Pz/woman-sult-002.jpg",
      name: "woman-suit 002",
      price: 9999,
      category: "women suit",
      rating: 4.5,
      menSuit: false,
      menPants: false,
      womanPants: false,
      womanSuits: true,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },
    {
      images: "https://i.postimg.cc/0NJg9gjv/women-sult-004.jpg",
      name: "woman-suit 003",
      price: 9999,
      category: "women suit",
      rating: 4.5,
      menSuit: false,
      menPants: false,
      womanPants: false,
      womanSuits: true,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },
    {
      images: "https://i.postimg.cc/bY5Q2KNW/women-Sult-004.jpg",
      name: "woman-suit 004",
      price: 9999,
      category: "women suit",
      rating: 4.5,
      menSuit: false,
      menPants: false,
      womanPants: false,
      womanSuits: true,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },
    {
      images: "https://i.postimg.cc/NM4BTsL0/blazersult.jpg",
      name: "woman-suit 005",
      price: 9999,
      category: "women suit",
      rating: 4.5,
      menSuit: false,
      menPants: false,
      womanPants: false,
      womanSuits: true,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },
    {
      images: "https://i.postimg.cc/DZp86CDL/blazercoat.jpg",
      name: "woman-suit 006",
      price: 9999,
      category: "women suit",
      rating: 4.5,
      menSuit: false,
      menPants: false,
      womanPants: false,
      womanSuits: true,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },
    {
      images: "https://i.postimg.cc/N08y93Xj/Azblazer.jpg",
      name: "woman-suit 07",
      price: 9999,
      category: "women suit",
      rating: 4.5,
      menSuit: false,
      menPants: false,
      womanPants: false,
      womanSuits: true,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },
    //   Banner logo
    {
      images: "https://i.postimg.cc/JzDN6CRV/png-transparent-paris.png",
      name: "Banner logo",
      price: 9999,
      category: "men suit",
      rating: 4.5,
      menSuit: false,
      menPants: false,
      womanPants: false,
      womanSuits: false,
      newProducts: false,
      bannerImages: true,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },
    //   Logo
    {
      images: "https://i.postimg.cc/Qx4Lg1dY/fashion-logo.jpg",
      name: "display logo",
      price: 9999,
      category: "men suit",
      rating: 4.5,
      menSuit: false,
      logo: true,
      menPants: false,
      womanPants: false,
      womanSuits: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },

    //   Womans pants
    {
      images: "https://i.postimg.cc/PrjXPmFg/womanblack-002.jpg",
      name: "woman pants",
      price: 9999,
      category: "men suit",
      rating: 4.5,
      menSuit: false,
      menPants: false,
      womanPants: true,
      womanSuits: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },
    {
      images: "https://i.postimg.cc/G3krw4hq/woman-pants-001.jpg",
      name: "woman pants2",
      price: 9999,
      category: "men suit",
      rating: 4.5,
      menSuit: false,
      menPants: false,
      womanPants: true,
      womanSuits: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },
    {
      images: "https://i.postimg.cc/ZRtgVL3Z/woman-Pant-004.jpg",
      name: "woman pant4",
      price: 9999,
      category: "men suit",
      rating: 4.5,
      menSuit: false,
      menPants: false,
      womanPants: true,
      womanSuits: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },
    {
      images: "https://i.postimg.cc/ZRtgVL3Z/woman-Pant-004.jpg",
      name: "woman pant2 3",
      price: 9999,
      category: "men suit",
      rating: 4.5,
      menSuit: false,
      menPants: false,
      womanPants: true,
      womanSuits: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },
    {
      images: "https://i.postimg.cc/B6pgH5Bm/women-Leg-Pants-Ami.jpg",
      name: "Ami pants 1",
      price: 9999,
      category: "men suit",
      rating: 4.5,
      menSuit: false,
      menPants: false,
      womanPants: true,
      womanSuits: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },
    {
      images: "https://i.postimg.cc/Kz8LX6t5/woman-Trousers.webp",
      name: "Ami pants",
      price: 9999,
      category: "women pants",
      rating: 4.5,
      menSuit: false,
      menPants: false,
      womanPants: true,
      womanSuits: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },
    {
      images: "https://i.postimg.cc/1RTFTYXp/womens-Long-Leg-Pant.jpg",
      name: "leg  long",
      price: 9999,
      category: "women pants",
      rating: 4.5,
      menSuit: false,
      menPants: true,
      womanSuits: false,
      womanPants: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },
    //   Men Pants
    {
      images: "https://i.postimg.cc/vTqDrTjR/men-pants-001.jpg",
      name: "men pants 001",
      price: 9999,
      category: "men pants",
      rating: 4.5,
      menSuit: false,
      menPants: true,
      womanSuits: false,
      womanPants: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },
    {
      images: "https://i.postimg.cc/htgPX9hJ/men-Pants-004.jpg",
      name: "men pants 002",
      price: 9999,
      category: "men pants",
      rating: 4.5,
      menSuit: false,
      menPants: true,
      womanSuits: false,
      womanPants: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },
    {
      images: "https://i.postimg.cc/BbTf3VTm/men-Pants-005.jpg",
      name: "pants 005",
      price: 9999,
      category: "men pants",
      rating: 4.5,
      menSuit: false,
      menPants: true,
      womanSuits: false,
      womanPants: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },
    {
      images: "https://i.postimg.cc/90pgJ5tH/men-Pants-006.jpg",
      name: "pants 006",
      price: 9999,
      category: "men pants",
      rating: 4.5,
      menSuit: false,
      menPants: true,
      womanSuits: false,
      womanPants: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },
    {
      images: "https://i.postimg.cc/fTqBLv8C/men-Pents-002.jpg",
      name: "menPants002",
      price: 9999,
      category: "men pants",
      rating: 4.5,
      menSuit: false,
      menPants: true,
      womanSuits: false,
      womanPants: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },
    {
      images: "https://i.postimg.cc/1tMDd9TB/men-Pants-007.webp",
      name: "men pants 007",
      price: 9999,
      category: "men pants",
      rating: 4.5,
      menSuit: false,
      menPants: true,
      womanSuits: false,
      womanPants: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },
    {
      images: "https://i.postimg.cc/kG0G1znw/men-Pants-008.webp",
      name: "men pants 008",
      price: 9999,
      category: "men pants",
      rating: 4.5,
      menSuit: false,
      menPants: true,
      womanSuits: false,
      womanPants: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },
    {
      images: "https://i.postimg.cc/htgPX9hJ/men-Pants-004.jpg",
      name: "men pants 004",
      price: 9999,
      category: "men pants",
      rating: 4.5,
      menSuit: false,
      menPants: true,
      womanSuits: false,
      womanPants: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: false,
    },
    // Scrolling images
    {
      images: "https://i.postimg.cc/GpdgDsZp/ffice-profession-dress1.jpg",
      name: "scrolling-images ",
      price: 9999,
      category: "men pants",
      rating: 4.5,
      menSuit: false,
      menPants: false,
      womanSuits: false,
      womanPants: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: true,
    },
    {
      images: "https://i.postimg.cc/QtpghX8W/complete-Officedress.jpg",
      name: "men cloths",
      price: 9999,
      category: "men pants",
      rating: 4.5,
      menSuit: false,
      menPants: false,
      womanSuits: false,
      womanPants: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: true,
    },
    {
      images: "https://i.postimg.cc/8C7tQQfh/office-suit02.png",
      name: "suit lady",
      price: 9999,
      category: "men pants",
      rating: 4.5,
      menSuit: false,
      menPants: false,
      womanSuits: false,
      womanPants: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: true,
    },
    {
      images: "https://i.postimg.cc/52Jqjksz/clths02.jpg",
      name: "green jacket",
      price: 9999,
      category: "men pants",
      rating: 4.5,
      menSuit: false,
      menPants: false,
      womanSuits: false,
      womanPants: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: true,
    },
    {
      images: "https://i.postimg.cc/fWCXKqJZ/ladyoutfit.png",
      name: "lady outfit",
      price: 9999,
      category: "men pants",
      rating: 4.5,
      menSuit: false,
      menPants: false,
      womanSuits: false,
      womanPants: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: true,
    },
    {
      images: "https://i.postimg.cc/283XK2qp/officewear5.jpg",
      name: "office wear",
      price: 9999,
      category: "men pants",
      rating: 4.5,
      menSuit: false,
      menPants: false,
      womanSuits: false,
      womanPants: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: true,
    },
    {
      images: "https://i.postimg.cc/cHdjHWX2/ladyofficeswear4.jpgv",
      name: "lady wear",
      price: 9999,
      category: "men pants",
      rating: 4.5,
      menSuit: false,
      menPants: false,
      womanSuits: false,
      womanPants: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: true,
    },
    {
      images: "https://i.postimg.cc/6qPzKx8k/mens-fashion-dress-shirt03.png",
      name: "mens-fashion-dress-shirt",
      price: 9999,
      category: "men pants",
      rating: 4.5,
      menSuit: false,
      menPants: false,
      womanSuits: false,
      womanPants: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: true,
    },
    {
      images: "https://i.postimg.cc/655yJGwx/womensuit.jpg",
      name: "lady red suit",
      price: 9999,
      category: "men pants",
      rating: 4.5,
      menSuit: false,
      menPants: false,
      womanSuits: false,
      womanPants: false,
      newProducts: false,
      bannerImages: false,
      categories: false,
      advertImages: false,
      scrollImages: true,
    },
  ],
};

module.exports = data;
